name: Earendil
services:
  backend:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports: 
      - 8000:8000
    volumes:
      - ../backend/:/app
    depends_on:
      - "db"
    environment:
      DATABASE_URL: postgresql://research_user:research_password@db:5432/Earendil
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: research_user
      POSTGRES_PASSWORD: research_password
      POSTGRES_DB: Earendil
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
    