name: Earendil
services:

  #database:
    #image: postgres
      # etc..
    #environment:

  backend:
    image: earendil-backend:1.0
    ports: 
      - 8000:8000
    environment:
      #
    depends_on:
      - "database"
    