# Greeting test
GET http://localhost:8000/
Accept: application/json

###
# Status tests
GET http://localhost:8000/status
Accept: application/json

###
POST http://localhost:8000/messages 
Content-Type: application/json

{
    "name": "hello!"
}

###
# Status tests
GET http://localhost:8000/status
Accept: application/json

###
PUT http://localhost:8000/status 
Content-Type: application/json

{
    "status": "sick"
}
###
PUT http://localhost:8000/status 
Content-Type: application/json

{
    "status": "healthy"
}
###
